export interface GmailPushQueueMessage {
  userId: string;
  pubSubBody: string;
}

// Env is generated by `wrangler types` in worker-configuration.d.ts
// Extend here only for queue message typing
export type AppEnv = Env & {
  GMAIL_PUSH_QUEUE: Queue<GmailPushQueueMessage>;
};

export type HonoContext = {
  Bindings: AppEnv;
};
